version: "3.3"

services:
    node-red:
        image: wagoautomation/node-red-iot-amd:latest
        container_name: node-red
        restart:
            always
        ports:
            - "18800:1880"
        # networks:
            # - iot-stack
        volumes:
            - ./volumes/node-red:/data

    influxdb:
        image: influxdb:2.0
        container_name: influxdb
        restart:
            always
        ports:
            - "18086:8086"
       # networks:
           # - iot-stack
        volumes:
            - ./volumes/influxdb:/var/lib/influxdb
        environment:    
            - INFLUXDB_DB=${INFLUXDB_DATABASE}
            - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
            - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        user: "0"
        restart:
            always
        ports:
            - "13000:3000"
        # networks:
            # - iot-stack
        volumes:
            - ./volumes/grafana:/var/lib/grafana
            - ./volumes/grafana/grafana-provisioning/:/etc/grafana/provisioning
        depends_on:
            - influxdb
        environment:
            - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
            - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
            
    mosquitto:
        image: eclipse-mosquitto:latest
        ports:
            - "11883:1883"
            - "18883:8883"
        volumes:
            - ./volumes/mosquitto:/mosquitto
            - ./volumes/mosquitto/config:/mosquitto/config
        # networks:
            # - iot-stack

# networks:
    # iot-stack:
        # driver: bridge
